#!/bin/bash

# Domain expiration check for Checkmk monitoring system, v0.1
# Tested with CentOS 8 and Checkmk 1.6.0p16
# Place the script under /usr/lib/check_mk_agent/local/
#
# Originally a Nagios check, converted to Checkmk format per 
# https://checkmk.com/cms_localchecks.html syntax.
# Please note that script depends a lot of how whois database
# returns the expiration date, so errors can occur so adjust
# DATE_EXP accordingly.

# List domains to be checked, separated by commma: domain1.com,domain2.net etc.
DOMAINS="example.com"
WARNING="29"
CRITICAL="25"

echo "<<<local>>>"
for domain in $(echo $DOMAINS | sed "s/,/ /g")
do
	DATE_EXP=$(whois $domain | grep "Expiration Date\|Registry Expiry" | grep '[0-9]\+' | awk '{print $NF}' | uniq)
	DATE_NOW=$(date +%s)
	DAYS=$(( -(($DATE_NOW) - $(date +%s --date "$DATE_EXP") )/(3600*24)))

	if [[ $DAYS -le $CRITICAL ]];
        	then echo "2 Domain_${domain} - CRIT - Domain '$domain' expires in $DAYS days" ;
	elif [[ $DAYS -le $WARNING ]];
        	then echo "1 Domain_${domain} - WARN -  Domain '$domain' expires in $DAYS days" ;
	else
		echo "0 Domain_${domain} - OK - Domain '$domain' expires in $DAYS days" ;
	fi
done
